version: "2"
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
  consul2:
    image: "progrium/consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul"
    depends_on:
      - consul
  consul3:
    image: "progrium/consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul"
    depends_on:
      - consul


  nginx-lb:
    build: nginx/
    ports:
      - 9008:9008
    expose:
      - 9008
    links:
      - consul
    restart: always
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"
    volumes:
        - /tmp


  api-email:
    build: email_ser/
    #container_name: app1
    ports:
      - "9008"
    links:
      - consul
      - nginx-lb
    volumes_from:
      - nginx-lb

